[tool.black]
line-length = 100
target-version = ["py312"]
include = "\.(py|pyi)$"
exclude = "^/\.(venv|git|ruff_cache|mypy_cache)/"

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [".venv", "build", "dist", ".git"]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
ignore = [
]

